version: "3.3"

services:
  # FastAPI service
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant_menu_api_app
    ports:
      - "8000:8000" # Expose port 8000 for FastAPI
    depends_on:
      - db # Ensure PostgreSQL is available before FastAPI starts
    environment:
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
    volumes:
      - .:/app # Mount the app code to allow for live code updates (optional)

  # PostgreSQL service
  db:
    image: postgres:17-alpine3.21
    container_name: postgres_db
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "5432:5432" # Expose port 5432 for PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent data storage

# Volumes for persistent PostgreSQL data
volumes:
  postgres_data:
